__base__: config/default.yaml
test_size: 0
general:
  transformer:
    max_order: 0
    n_bins: -1
    agg_length: true
    n_first: 0
    n_last: 0
    n_top: 0
    n_top_prop: 0
    max_order: 0
    max_agg_order: 0
    agg_functions: []
  sequential:
    seq_len_list: [1000000, 10000, 100, 1]
    embed_dim_list: [128, 128, 128, 128]
    num_blocks_list: [2, 2, 2, 2]
    num_heads_list: [2, 2, 2, 2]
    context_list:
      - []
      - []
      - []
      - []
      - []
    max_batch_size: 65535
    grad_checkpointing: true #to save memory during training but increases training time
    use_global_cond: false
    use_padding_mask: false
    length_loss_weight: 0.0
    transformer_model: "gpt2"
  static:
    model_type: arf
train:
  sequential:
    epochs: 1000
    warmup_epochs: 20
    num_workers: 8
    batch_size: 8
    lr: 5.e-4
    min_lr: 0.0
    grad_clip: 0.1
    weight_decay: 0.0001
    chunk_size: 1000
    save_epoch: 200
generate:
  sequential:
    num_workers: 8
    batch_size: 256
    temperature: 0.01
    len_temperature: 0.01
    chunk_size: 1000
    use_stop_token: false