__base__: config/default.yaml
test_size: 0
general:
  sequential:
    seq_len_list: [160000, 8000, 400, 20, 1]
    embed_dim_list: [768, 768, 768, 768, 768]
    num_blocks_list: [12, 12, 12, 12, 12]
    num_heads_list: [12, 12, 12, 12, 12]
    context_list:
      - []
      - []
      - []
      - []
      - []
    max_batch_size: 65535
    grad_checkpointing: true #to save memory during training but increases training time
    use_global_cond: true
    length_loss_weight: 0.0
    transformer_model: "gpt2"
    static_drop_prob: 0.3
  static:
    model_type: ctgan
train:
  sequential:
    epochs: 200
    warmup_epochs: 10
    num_workers: 8
    batch_size: 1
    lr: 2.e-4
    min_lr: 0.0
    lr_schedule: cosine
    grad_clip: 1.0
    weight_decay: 0.01
    chunk_size: 1000
    validation_split: 0.1
    validation_freq: 1
    early_stop_patience: 0
    early_stop_delta: 0.0
    save_epoch: 400
    auto_adjust_batch_size: true
    min_batch_size: 1
    max_batch_size: 1024
    memory_threshold: 0.90
generate:
  sequential:
    num_workers: 8
    batch_size: 1024
    temperature: 1
    len_temperature: 1
    use_stop_token: false